
// A Javascript program for Dijkstra's
// single source shortest path
// algorithm. The program is for
// adjacency matrix representation
// of the graph.
let NO_PARENT = -1;

//Put this in the beginning of the script
var start = new Date().getTime();

function dijkstra(adjacencyMatrix,startVertex,endVertex,shortestDistances, parents)
{
    
	let nVertices = adjacencyMatrix[0].length;

		// shortestDistances[i] will hold the
		// shortest distance from src to is
		shortestDistances = new Array(nVertices);

		// added[i] will true if vertex i is
		// included / in shortest path tree
		// or shortest distance from src to
		// i is finalized
		let added = new Array(nVertices);

		// Initialize all distances as
		// INFINITE and added[] as false
		for (let vertexIndex = 0; vertexIndex < nVertices;
											vertexIndex++)
		{
			shortestDistances[vertexIndex] = Number.MAX_VALUE;
			added[vertexIndex] = false;
		}
		
		// Distance of source vertex from
		// itself is always 0
		shortestDistances[startVertex] = 0;

		// Parent array to store shortest
		// path tree
		parents = new Array(nVertices);

		// The starting vertex does not
		// have a parent
		parents[startVertex] = NO_PARENT;

		// Find shortest path for all
		// vertices
		for (let i = 1; i < nVertices; i++)
		{

			// Pick the minimum distance vertex
			// from the set of vertices not yet
			// processed. nearestVertex is
			// always equal to startNode in
			// first iteration.
			let nearestVertex = -1;
			let shortestDistance = Number.MAX_VALUE;
			for (let vertexIndex = 0;
					vertexIndex < nVertices;
					vertexIndex++)
			{
				if (!added[vertexIndex] &&
					shortestDistances[vertexIndex] <
					shortestDistance)
				{
					nearestVertex = vertexIndex;
					shortestDistance = shortestDistances[vertexIndex];
				}
			}

			// Mark the picked vertex as
			// processed
			added[nearestVertex] = true;

			// Update dist value of the
			// adjacent vertices of the
			// picked vertex.
			for (let vertexIndex = 0;
					vertexIndex < nVertices;
					vertexIndex++)
			{
				let edgeDistance = adjacencyMatrix[nearestVertex][vertexIndex];
				
				if (edgeDistance > 0
					&& ((shortestDistance + edgeDistance) <
						shortestDistances[vertexIndex]))
				{
					parents[vertexIndex] = nearestVertex;
					shortestDistances[vertexIndex] = shortestDistance +
													edgeDistance;
				}
			}
		}
    return printSolution(startVertex, shortestDistances, parents, endVertex);
}

function printSolution(startVertex,distances,parents,endVertex)
{
		console.log("Vertex   Distance   Path");

        console.log("From -> To: " + startVertex + " -> " + endVertex);
        //shortest distance
        console.log("Total Distance: " + distances[endVertex]);

        //prints to the path
        printPath(endVertex, parents);
        return distances[endVertex];
}

function printPath(currentVertex,parents)
{
    	// parents is an array to store shortest
		// path tree cause I forget

	    // Base case : Source node has
		// been processed
		if (currentVertex == NO_PARENT)
		{
			return;
		}
		printPath(parents[currentVertex], parents);
		console.log(currentVertex + " ");
}

let INF =  1e7;
let graph = [ [0,	28.07,	72.21,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[28.07,	0,	INF,	72.21,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[72.21,	INF,	0,	28.07,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	72.21,	28.07,	0,	INF,	49.99,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	0,	22.01,	86.05,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	49.99,	22.01,	0,	INF,	86.05,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	86.05,	INF,	0,	22.01,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	40.56,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	86.05,	22.01,	0,	83.57,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	83.57,	0,	73.42,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	73.42,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	112.77,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	88.43,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	121.99,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	88.43,	0,	40.93,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	40.93,	0,	16.9,	100.93,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	16.9,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	65.42,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	100.93,	INF,	0,	23.53,	INF,	68.59,	INF,	INF,	INF,	INF,	INF,	INF,	60.37,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	23.53,	0,	24.05,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	40.56,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	24.05,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.59,	INF,	INF,	0,	40.6,	71.78,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	40.6,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	71.78,	INF,	0,	17.49,	40.93,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	112.77,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	17.49,	0,	INF,	40.93,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	40.93,	INF,	0,	17.49,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	40.93,	17.49,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	76.07,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	33.53,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	60.37,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	33.53,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	65.42,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	121.99,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	27.33,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	76.91,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	27.33,	0,	21.39,	46.47,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	21.39,	0,	INF,	46.47,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	46.47,	INF,	0,	21.39,	56.34,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	46.47,	21.39,	0,	INF,	56.34,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	56.34,	INF,	0,	21.39,	INF,	44.03,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	56.34,	21.39,	0,	44.03,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	44.03,	0,	24.88,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	59.04,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	44.03,	INF,	24.88,	0,	68.61,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.61,	0,	20.36,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	20.36,	0,	33.44,	INF,	57.98,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	33.44,	0,	57.98,	INF,	INF,	INF,	INF,	INF,	38.63,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	57.98,	0,	33.44,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	57.98,	INF,	33.44,	0,	77.76,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	76.07,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	77.76,	0,	66.96,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	66.96,	0,	26.07,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	26.07,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	56.66,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	48.81,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	38.63,	INF,	INF,	INF,	INF,	INF,	48.81,	0,	21.37,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	21.37,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.36,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	59.04,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	36.71,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	36.71,	0,	83.65,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	83.65,	0,	58.7,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	76.91,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	58.7,	0,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	0,	58.7,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	58.7,	0,	83.65,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	83.65,	0,	36.71,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	36.71,	0,	72.51,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.36,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	72.51,	0,	31.68,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	31.68,	0,	103.19,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	56.66,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	103.19,	0,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	0,	33.65,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	133.44,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	33.65,	0,	39.64,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	39.64,	0,	27.03,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	27.03,	0,	68.87,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	42.19,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.87,	0,	72.36,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	72.36,	0,	63.32,	INF,	INF,	INF,	INF,	49.15,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	63.32,	0,	34.25,	INF,	INF,	49.15,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	34.25,	0,	42.98,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.5,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	42.98,	0,	62.25,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	62.25,	0,	INF,	INF,	INF,	INF,	INF,	69.73,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	49.15,	INF,	INF,	INF,	0,	64.08,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	49.15,	INF,	INF,	INF,	INF,	64.08,	0,	INF,	INF,	42.06,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	42.19,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	43.33,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	43.33,	0,	138.09,	INF,	INF,	INF,	47.59,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	42.06,	INF,	138.09,	0,	INF,	43.3,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	69.73,	INF,	INF,	INF,	INF,	INF,	0,	137.54,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF, INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	43.3,	137.54,	0,	46.73,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	24.17,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	46.73,	0,	96.75,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	47.59,	INF,	INF,	INF,	96.75,	0,	102.34,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	133.44,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	102.34,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	37.35,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	36.95,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	67.06,	54.52,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	36.95,	0,	41.77,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	41.77,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	52.2,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.52,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.46],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	105.23,	INF,	INF,	INF,	INF,	INF,	INF,	66.07],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	105.23,	0,	68.85,	INF,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	68.85,	0,	88.9,	INF,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	88.9,	0,	45.39,	INF,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	45.39,	0,	28.62,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	28.62,	0,	INF,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	24.17,	INF,	INF,	INF,	37.35,	67.06,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	54.52,	INF,	52.2,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF],
[INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	55.46,	66.07,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0] ];

//let path;
//gonna use dictionary cause I dont like this.
const map = new Map();
map.set("NH", 2);
map.set("CY", 16);
map.set("TS", 18);
map.set("LA", 18);
map.set("MZ", 25);
map.set("SN", 35);
map.set("SH", 30);
map.set("LO", 38);
map.set("EH", 43);
map.set("SC", 51);
map.set("JR", 51);
map.set("ST", 52);
map.set("BP", 55);
map.set("CS", 55);
map.set("BH", 67);
map.set("UL", 61);
map.set("MG", 59);
map.set("SQ", 70);
map.set("AR", 74);
map.set("JD", 75);
map.set("BB", 79);
map.set("NA", 80);
map.set("EA", 89);
map.set("CH", 84);
map.set("LL", 84);
map.set("SG", 85);
map.set("LH", 86);
//Parking Spots
map.set("B1", 10);
map.set("B3", 26);
map.set("G3", 40);
map.set("B5", 81);
map.set("B6", 82);
map.set("E6", 85);

let hi = "JR BH SH";
const words = hi.split(' ');


//determining parking location start vertex in a sense
    // B1: 10
    // B3: 26
    // G3: 40
    // B5: 81
    // B6: 82
    // E6: 85
    const park = ["B1", "B3", "G3", "B5", "B6", "E6"];
    let dis2 = map.get(words[0]);
    let shortestDistances = [];
    let parents = [];
    //console.log("Checking: "+map.get(park[0]));
    //Returns Total Distance of the Parking Location to Final Destination
    let startCompare = dijkstra(graph,map.get(park[0]),dis2,shortestDistances,parents);
    let parkingLocationString;

    for(let i = 1; i < park.length; i++){
        let dis1 = map.get(park[i]);
        //gets the first entry of the word

        //use djikstra to determine which parking lot is the shortest from parking lot
        
        //console.log(park[i]);
        //should return Distance 
        let distCompare = dijkstra(graph,dis1,dis2,shortestDistances,parents);
        if(distCompare < startCompare)
        {
            startCompare = map.get(park[i]);
            parkingLocationString = park[i];
        }

    }
    console.log("Closest Park Location At: " + parkingLocationString);
    startVertex = startCompare;
    //endVertex = words[words.length-1];
    for(let i = 0; i < words.length; i++){
        endVertex = map.get(words[i]);
        dijkstra(graph,startVertex, endVertex,shortestDistances,parents);
        //printSolution(startVertex,shortestDistances,parents,endVertex);
        startVertex = map.get(words[i]);
    }

    var end = new Date().getTime();
    var time = end - start;
    console.log('Execution time: ' + time);